CREATE DATABASE WEB_PAGE;
use web_page;
CREATE TABLE game(
	IP INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	LENGTH INT NOT NULL,
	WEB_NAME VARCHAR(10) NOT NULL
);

INSERT INTO game VALUE (001,3,'baidu');
INSERT INTO game VALUES 
	(002,3,'baidu'),
	(003, 4, 'tenct'),
	(004, 5, 'ali')
;